---
- name: Provision nat_server
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Flush iptables
    iptables:
      flush: true
  - name: Setup IP fowarding and masquerading
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: eth0
      jump: MASQUERADE
      protocol: all
  - name: Install `iptables-persistent` and related packages
    apt:
      pkg:
        - iptables-persistent
        - netfilter-persistent
      state: present
  - name: Enable kernel packet forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
