---
- name: Provision web_server
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Configure firewall
    ufw:
      rule: allow
      name: Apache Full
  - name: Install PHP packages
    apt:
      pkg:
        - php
        - php-bcmath
        - php-common
        - php-gd
        - php-intl
        - php-mbstring
        - php-mysql
        - php-zip
      state: present
